// Generated by Wrangler on Fri Sep 13 2024 02:08:13 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	PUBLIC_JWK_CACHE_KV: KVNamespace;
	PUBLIC_JWK_CACHE_KEY: "public-jwk-cache-key";
	SECRETS_SERVICE_ACCOUNT_JSON_STRING: string;
	SECRETS_DATABASE_URL: string;
}
