// Generated by Wrangler on Sun Sep 08 2024 12:53:35 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	PUBLIC_JWK_CACHE_KV: KVNamespace;
	PUBLIC_JWK_CACHE_KEY: "public-jwk-cache-key";
	DB_TEST1: D1Database;
}
