// Generated by Wrangler on Fri Sep 13 2024 12:50:11 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	SECRETS_SERVICE_ACCOUNT_JSON_STRING: string;
	SECRETS_DATABASE_URL: string;
	DB_TEST_API_REACT_1: D1Database;
}
