// Generated by Wrangler by running `wrangler types`

interface Env {
	KV_INPUTS_PUBLIC_JWK_CACHE: KVNamespace;
	KV_INPUTS_PUBLIC_JWK_CACHE_KEY: "KV_INPUTS_PUBLIC_JWK_CACHE_KEY";
	PUBLIC_FIREBASE_PROJECT_ID: string;
	DB_INPUTS: D1Database;
}
