// Generated by Wrangler on Mon Sep 16 2024 07:53:58 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	PUBLIC_JWK_CACHE_KV: KVNamespace;
	PUBLIC_JWK_CACHE_KEY: "public-jwk-cache-key";
	SECRETS_SERVICE_ACCOUNT_JSON_STRING: string;
	SECRETS_DATABASE_URL: string;
	PUBLIC_FIREBASE_PROJECT_ID: string;
}
