name = "inputs-api"

compatibility_date = "2024-05-24"

[limits]
cpu_ms = 100 # To prevent accidental runaway bills or denial-of-wallet attacks (maybe ignored on free-plan)

[vars]
# Specify cache key to store and get public jwk.
PUBLIC_FIREBASE_PROJECT_ID = "inputs-prd" # override in .dev.vars in local development (need this because this package doesn't use vite env on build step)
KV_INPUTS_PUBLIC_JWK_CACHE_KEY = "KV_INPUTS_PUBLIC_JWK_CACHE_KEY"

[[ d1_databases ]]
binding = "DB_INPUTS"
database_name = "inputs-prd" # used by "wrangler d1 migrations [database_name]"
database_id = "80741dbc-15dc-4e0b-841e-1717b4d358b2" # db=inputs-prd
preview_database_id = "93b1104f-2f18-4530-a115-0cfc45f39822" # db=inputs-preview (used by wrangler dev command)
migrations_dir = "drizzle" # load as symlink from packages/database/wrangler.toml

[[kv_namespaces]]
binding = "KV_INPUTS_PUBLIC_JWK_CACHE"
id = "184e53d4ddf641ba9b8069f642fc76f0" # kv_namespace=inputs-prd
preview_id = "5390c3fd19f3435faa9966988ab9677b" # kv_namespace=inputs-preview (used by wrangler dev command)

#[[ d1_databases ]]
#binding = "DB_TEST1"
#database_name = "test1" # used by "wrangler d1 migrations [database_name]"
#database_id = "ff259bbd-8d7b-4da7-b709-e3850df4ca63" # db=test1
#preview_database_id = "0e0d1164-e7f3-42db-87c4-fc9819abc4f1" # db=test1-preview
#migrations_dir = "../../packages/database/drizzle"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"