name: test
on:
  push:
  workflow_dispatch:

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Enable corepack for pnpm
        run: corepack enable pnpm

      - name: Setup & Restore Node cache
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Restore turbo cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: .turbo/cache
          key:
            turbo/${{ github.job }}/${{ github.ref_name }}/${{ github.sha }}
          restore-keys: |
            turbo/${{ github.job }}/${{ github.ref_name }}/
            turbo/${{ github.job }}/

      - name: Lint check
        run: pnpm lint

      - name: Type check
        run: pnpm typecheck

      - name: Build check
        run: pnpm build
